#!/usr/bin/env bash

exists() {
    which $1 &> /dev/null;
}

cd "$HOME" || exit

# ─────────────────────────────────────────────────────────

echo "configure dotfiles..."

export DOTFILES="$HOME/.dotfiles"

if [ -d "$DOTFILES" ]; then
    echo "Dotfiles have already been cloned into the home dir"
else
    echo "Cloning .dotfiles repository into $DOTFILES"
    git clone https://github.com/Skarmux/.dotfiles $DOTFILES
fi

echo "updating dotbot sub-repository to latest..."
cd "$DOTFILES" || "Didn't cd into dotfiles"
git submodule update --init --recursive

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# ─────────────────────────────────────────────────────────

DISTRO="`lsb_release -i | cut -f 2-`"
echo "detected distribution: $DISTRO"

echo "─────────────────────────────────────────────────────────"
echo "install packages..."

packages=(
    git
    gcc
)

for p in "${packages[@]}"; do
    if ! exists $p; then
        echo "installing $p..."
        case $DISTRO in
            'Debian')
                sudo apt install $p
                ;;
            'Fedora')
                sudo dnf install $p
                ;;
            'Arch')
                sudo pacman -S $p
                ;;
        esac
    else
        echo "$p already installed" 
    fi
done

if ! exists "hx"; then
    case $DISTRO in
        "Ubuntu")
            sudo add-apt-repository ppa:maveonair/helix-editor
            sudo apt update
            sudo apt install helix
            ;;
        "Fedora")
            sudo dnf copr enable varlad/helix
            ;;
        'Arch')
            sudo pacman -S helix
            ;;
    esac
fi

# ─────────────────────────────────────────────────────────

if ! exists rustc; then
    echo "─────────────────────────────────────────────────────────"
    echo "install rust environment..."
    curl https://sh.rustup.rs -sSf | sh
    $HOME/.cargo/bin/rustup default nightly
    $HOME/.cargo/bin/rustup update
fi

crates=(
    starship
    dust
    zellij
    mprocs
    gitui
    irust
    bacon
    porsmo
    rg
    sccache
    bat
    exa
    coreutils
    rtx
)

for p in "${crates[@]}"; do
    if ! exists $p; then
        echo "─────────────────────────────────────────────────────────"
        echo "installing $p..."
        cargo install $p
    else
        echo "$p already installed"  
    fi
done

# ─────────────────────────────────────────────────────────

echo "─────────────────────────────────────────────────────────"
echo "done."

exit 0
